name: Terraform Destroy

on:
  workflow_dispatch:  # ✅ This allows you to manually trigger the workflow from the GitHub Actions UI

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: "."

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Destroy
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} destroy -auto-approve
